### ISSUE TITLE
MismatchedInputException

### ISSUE THREAD

**Issue by klmi** [pipauwel/IFC.JAVA#6]
Hi,

while loading your sample the following error occures:

```
private void sample() {
         InputStream is = null;
         try {
             String filePath = "sample.ifcxml";
             File xml = new File(filePath);
             is = new FileInputStream(xml);
             XmlMapper m = new XmlMapper();
             m.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
             m.configure(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, true);
             m.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
             IfcProject proj = m.readValue(is, IfcProject.class);
             IfcLabel s = proj.getName();
             System.out.println(s.getValue());
         } catch (Exception ex) {
             System.out.println(ex.getMessage());
             Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
         } finally {
             //ignore null for now
                     is.close();
         }
     }
```

```
Cannot construct instance of `com.buildingsmart.tech.ifc.IfcKernel.IfcProject` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (FileInputStream); line: 2, column: 1]
Nov 13, 2020 8:35:22 AM de.comp.Main start
SCHWERWIEGEND: null
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.buildingsmart.tech.ifc.IfcKernel.IfcProject` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (FileInputStream); line: 2, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1329)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1275)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1235)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:192)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1156)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserializeWithType(WrapperHandlingDeserializer.java:137)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at de.comp.Main.start(Main.java:35)
	at de.comp.Main.main(Main.java:21)
```

Any ideas what I might be doing wrong?

**Comment by pipauwel** [comment]
Thanks for posting this issue. The project is however not actively maintained any more and also closed now. My apologies and hopefully you will find better resources.
