### ISSUE TITLE
The following error occurred during file conversion

### ISSUE THREAD

**Issue by gisspace** [pipauwel/IFC.JAVA#7]
The following error occurred during file conversion：

Exception in thread "main" java.lang.IllegalArgumentException: Can not set com.buildingsmart.tech.ifc.IfcMeasureResource.IfcValue field com.buildingsmart.tech.ifc.IfcPropertyResource.IfcPropertySingleValue.nominalValue to com.buildingsmart.tech.ifc.IfcMeasureResource.IfcLogical
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.buildingsmart.tech.IO.IfcParser.loadToClassLibrary(IfcParser.java:324)
	at com.buildingsmart.tech.IO.IfcParser.parseModelFromSPF(IfcParser.java:200)
	at com.buildingsmart.tech.IO.IfcParser.main(IfcParser.java:102)

**Comment by pipauwel** [comment]
Thanks for posting this issue. The project is however not actively maintained any more and also closed now. My apologies and hopefully you will find better resources.
